title: Ghannam Aljabari Blog

# GitHub Pages settings
theme: jekyll-theme-primer

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Plugins
plugins:
  - jekyll-github-metadata
  - jekyll-seo-tag

# Exclude files
exclude:
  - README.md
  - "*.gem"
  - "*.gemspec"

# Collections for blog posts
collections:
  posts:
    output: true
    permalink: /:name/

# Default layouts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: default
  - scope:
      path: ""
    values:
      layout: default
